# Generated by Django 3.0.4 on 2020-03-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50, verbose_name='Название Предмета')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Group')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Specialty')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_title', models.CharField(max_length=5, verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Subject')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
