# Generated by Django 3.0.4 on 2020-03-16 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_mark_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время оценки'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_degree',
            field=models.CharField(default=1, max_length=200, verbose_name='Научная степень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_position',
            field=models.CharField(default=1, max_length=200, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sex',
            field=models.CharField(choices=[('N', 'Не указанно'), ('M', 'Мужчина'), ('F', 'Женщина')], default='N', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_sex',
            field=models.CharField(choices=[('N', 'Не указанно'), ('M', 'Мужчина'), ('F', 'Женщина')], default='N', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='СonnectionTSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Group')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Specialty')),
                ('teatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Teacher')),
            ],
        ),
    ]
