# Generated by Django 3.0.4 on 2020-03-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20200316_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сonnectiontsg',
            name='specialty',
        ),
        migrations.AddField(
            model_name='сonnectiontsg',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.Subject'),
            preserve_default=False,
        ),
    ]
