# Generated by Django 3.0.4 on 2020-03-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20200316_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сonnectiontsg',
            old_name='teatcher',
            new_name='teacher',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_datetime_start', models.DateTimeField(verbose_name='Время начала пары')),
                ('subject_datetime_stop', models.DateTimeField(verbose_name='Время конца пары')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Subject')),
            ],
        ),
    ]
