# Generated by Django 3.0.4 on 2020-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20200323_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('N/A', 'Не выбрано'), ('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница')], default='N/A', max_length=50, verbose_name='День недели'),
        ),
    ]
