# Generated by Django 3.0.4 on 2020-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20200323_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('N/A', 'Не выбрано'), ('M', 'Понедельник'), ('T', 'Вторник'), ('W', 'Среда'), ('TH', 'Четверг'), ('F', 'Пятница'), ('S', 'Субота')], default='N/A', max_length=3, verbose_name='День недели'),
        ),
    ]
